# list dirs
alias ldir='ls -p | grep -e / | cut -d / -f 1'
alias ldira='ls -ap | grep -e / | cut -d / -f 1'

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# space  ( free disk space )
alias space='df -h /'

# start fresh-by-cat
alias fbc='nohup node ~/Documents/github_dustinpfister/blog_posts/scripts/apps/fresh-by-cat/app.js 8000 > /dev/null &'